version: "2"
services:
  app:
    build: .
    command: npm run start
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
    env_file: .env
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: